http://localhost:8080/books

###

POST http://localhost:8080/books HTTP/1.1
content-type: application/json

{
    "name": "sample-book2",
    "content":"dasdnaidnadniandianiadiandandiandnasdaidnadindasdinadniandiadiandadiansidnadnaidnaidni"
}